<instance id="plant.1000000" docsrc = "BNC/A07">
<answer instance="plant.1000000" senseid="plant%factory"/>
<context>
Until the mid- and late 1970s, there were simply no rules whereby groupings of parents could obtain a state-financed, multi-denominational school, as the only channels of communication in these matters were those between the Department of Education and the relevant diocesan department or other church board. For example, a new housing estate would be built, the diocese would be informed of the development at the planning stage, and the diocesan office would put in for a school, or an extension for an existing school. The arrangement had been unchanged since the early years of the state and had become entirely natural. Similarly for the protestant community: the school  <head>plant</head>  is owned by the church, or appropriate church body.
</context>
</instance>

<instance id="plant.1000001" docsrc = "BNC/A0C">
<answer instance="plant.1000001" senseid="plant%factory"/>
<context>
Bodfari Foods is a processor and supplier of liquid milk. Last year the company saw pre-tax profits of 1.9m. JUS-ROL INVESTS POTATO product manufacturer Jus-Rol has invested 1.5m in its potato manufacturing  <head>plant</head>  at Amble, Northumberland. By the end of this month manufacturing capacity is expected to increase three-fold as a result, according to sales and marketing director Joe Weston. IDEAL CHANGE CATERING butcher Ideal Meat Supplies has moved from its Smithfield Market site to premises in North London. The company has also achieved a grade A accreditation from the plant evaluation committee of the National Association of Catering Butchers.
</context>
</instance>